name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y meson ninja-build libgtest-dev
    
    - name: Build & Test
      run: |
        meson setup builddir -Dtests=true
        meson compile -C builddir
        meson test -C builddir --verbose
